# Generated by Django 3.2 on 2022-02-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_alter_order_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_profile',
        ),
    ]
