# Generated by Django 3.2 on 2022-01-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=130),
        ),
    ]
