# Generated by Django 3.2 on 2022-01-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_person_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=130)),
                ('etype', models.CharField(blank=True, default='', max_length=130)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('econcern', models.TextField(blank=True)),
            ],
        ),
    ]
