# Generated by Django 3.2 on 2022-01-30 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='ename',
            new_name='cname',
        ),
    ]
