# Generated by Django 3.2 on 2022-02-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_rename_ename_enquiry_cname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, primary_key=True, serialize=False),
        ),
    ]
