# Generated by Django 3.2 on 2022-02-02 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20220202_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
